os: Visual Studio 2017
version: 1.1.0.{build}
configuration: Release
platform: Any CPU
skip_branch_with_pr: true
install:
- cmd: git submodule update --init --recursive
assembly_info:
  patch: true
  file: NppGist\Properties\AssemblyInfo.cs;NppGist.Tests\Properties\AssemblyInfo.cs;
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: >-
    nuget restore NppGist.sln
build:
  project: NppGist.sln
  verbosity: minimal
after_build:
- cmd: >-
    msbuild NppGist.sln /verbosity:minimal /p:Configuration=Release /p:Platform=x86
    
    msbuild NppGist.sln /verbosity:minimal /p:Configuration=Release /p:Platform=x64
test:
  assemblies:
  - NppGist.Tests\Unit\bin\x86\$(configuration)\*.Tests.dll
after_test:
- cmd: >-
    cd NppGist\bin

    7z a NppGist-x86-%APPVEYOR_BUILD_VERSION%.zip x86\%CONFIGURATION%\NppGist.dll

    7z a NppGist-x64-%APPVEYOR_BUILD_VERSION%.zip x64\%CONFIGURATION%\NppGist.dll
artifacts:
- path: bin\NppGist-x86-$(APPVEYOR_BUILD_VERSION).zip
  name: NppGist-x86
- path: bin\NppGist-x64-$(APPVEYOR_BUILD_VERSION).zip
  name: NppGist-x64