os: Visual Studio 2017
version: 1.1.0.{build}
configuration: Release
platform:
  - x86
  - x64
skip_branch_with_pr: true
install:
- cmd: git submodule update --init --recursive
assembly_info:
  patch: true
  file: NppGist\Properties\AssemblyInfo.cs;NppGist.Tests\Properties\AssemblyInfo.cs;
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: >-
    nuget restore NppGist.sln
build:
  project: NppGist.sln
  verbosity: minimal
test:
  assemblies:
  - NppGist.Tests\Unit\bin\$(PLATFORM)\$(CONFIGURATION)\*.Tests.dll
after_test:
- cmd: >-
    cd NppGist\bin\%PLATFORM%\%CONFIGURATION%

    7z a NppGist-%PLATFORM%-%APPVEYOR_BUILD_VERSION%.zip NppGist.dll
artifacts:
- path: NppGist\bin\%PLATFORM%\%CONFIGURATION%\NppGist-$(PLATFORM)-$(APPVEYOR_BUILD_VERSION).zip
  name: NppGist-$(PLATFORM)-$(APPVEYOR_BUILD_VERSION)